#!/bin/bash

######################################################################
#
# File      : binary
#
# Author    : Barry Kimelman
#
# Created   : April 22, 2021
#
# Purpose   : Generate a list of all the binary programs in the current directory
#
# Notes     : (none)
#
######################################################################

errors=0
opt_l=0
while getopts l opt
do
	case $opt in
	l)
		opt_l=1
		;;
	\?)
		errors=1
	esac
done

shift `expr $OPTIND - 1`

if [ $errors -eq 1 ]
then
	echo "$0 Aborted due to parameter errors."
	exit 1
fi

if [[ $opt_l == 1 ]]
then
	file * .[a-z0-9A-Z_]* | egrep 'ELF' | awk -F: '{print $1}' | while read filename
	do
		bkls2 $filename
	done
else
	file * .[a-z0-9A-Z_]* | egrep 'ELF' | awk -F: '{print $1}'
fi

exit 0

# bkls2: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=89695308828a90db206765f5155891ba44c528ac, for GNU/Linux 3.2.0, with debug_info, not stripped
